#ifndef GUARD_CONSTANTS_OTS_H
#define GUARD_CONSTANTS_OTS_H

#define OT_LOOKER_GROWLITHE    0
#define OT_LOOKER_TOXICROAK    1
#define OT_LOOKER_MAGIKARP     2
#define OT_PHOEBE_DUSKNOIR     3
#define OT_PHOEBE_SABLEYE      4
#define OT_PHOEBE_CERULEDGE    5
#define OT_SHELLY_HUNTAIL      6
#define OT_SHELLY_GOREBYSS     7
#define OT_EMMA_GUMSHOOS       8
#define OT_EMMA_MEOWSTIC       9
#define OT_LISIA_MISDREAVUS    10
#define OT_LISIA_MURKROW       11
#define OT_LOOKER_YANMEGA      12
#define OT_LOOKER_MAMOSWINE    13
#define OT_LOOKER_BRELOOM      14
#define OT_LOOKER_SHIINOTIC    15
#define OT_TEE_OVERQWIL        16
#define OT_TEE_DRAGALGE        17
#define OT_ALICE_TAUROS        18
#define OT_ALICE_MILTANK       19
#define OT_PAOLO_GALVANTULA    20
#define OT_PAOLO_PROBOPASS     21
#define OT_MAY_WALREIN         22
#define OT_MAY_CAMERUPT        23
#define OT_BLUE_GOLEM          24
#define OT_BLUE_MACHAMP        25
#define OT_BEATRICE_SWANNA     26
#define OT_BEATRICE_UNFEZANT   27
#define OT_LEO_SMEARGLE        28

#endif //GUARD_CONSTANTS_OTS_H