Looker_Text_WhatSeemsToBeTheProblem:
    .string "What seems to be the problem?$"

Looker_Text_CanIHelpYouWithSomething:
    .string "Can I help you with something?$"

Looker_Text_IsSomethingWrong:
    .string "Is something wrong?$"

Looker_Text_HowCanIHelp:
    .string "How can I help?$"

Looker_Text_Understood:
    .string "Understood.$"

Looker_Text_ThereHasToBeSomething:
    .string "There has to be something I can\n"
    .string "do to help.$"

Looker_Text_IdBeHappyToHelp:
    .string "I'd be happy to help.$"

Looker_Text_ICanCertainlyTry:
    .string "I can certainly try.$"

Looker_Text_ConsiderItDone:
    .string "Consider it done.$"
    
Looker_Text_IWillHandleThis:
    .string "I will handle this posthaste.$"

Looker_Text_GladICouldHelp:
    .string "Glad I could help.$"

Looker_Text_AnotherProblemSolved:
    .string "Another problem solved.$"

Looker_Text_OfCourse:
    .string "Of course.$"

Looker_Text_OfCourseICanHelp:
    .string "Of course I can help.$"
    
Looker_Text_SureICan:
    .string "Sure, I can!$"

Looker_Text_Indeed:
    .string "Indeed.$"

Looker_Text_WillDo:
    .string "Will do.$"
    
Looker_Text_LeaveItToMe:
    .string "Leave it to me.$"
    
Looker_Text_IWillAlwaysHelp:
    .string "Mission complete.$"

Looker_Text_AlrightFine:
    .string "Alright, fine.$"

Looker_Text_SoHeresTheThing:
    .string "So here's the thing…$"
    
Looker_Text_ThisSeemsSerious:
    .string "This seems like a serious problem.$"
    
Looker_Text_INeedYourHelp:
    .string "I need your help.$"

Looker_Text_Hmm:
    .string "Hmm…$"

Looker_Text_IHaveTheInformation:
    .string "I have the information you are looking\n"
    .string "for.$"

Looker_Text_WhatsWrong:
    .string "What's wrong?$"

Looker_Text_LetMeThinkAboutThat:
    .string "Let me think about that.$"

Looker_Text_ThankYouForYourHelp:
    .string "Thank you for your help.$"

Looker_Text_ThankYouForTheIntel:
    .string "Thank you for the intel.$"

Looker_Text_HereYouGo:
    .string "Here you go.$"

Looker_Text_NotYet:
    .string "Not yet.$"

Looker_Text_IFoundWhatYoureLookingFor:
    .string "I found what you're looking for.$"

Looker_Text_AllInADaysWork:
    .string "All in a day's work.$"
    
Looker_Text_WhatsThat:
    .string "Huh?\p"
    .string "What's that?$"

Looker_Text_Unlucky:
    .string "Unlucky.$"

Looker_Text_ThankYou:
    .string "Thank you.$"
    
Looker_Text_Sure:
    .string "Sure…$"

Looker_Text_Asleep:
    .string "Zzz…$"

Looker_Text_Uhh:
    .string "Uhh…$"
    
Looker_Text_Dots:
    .string "…$"

Looker_Text_DotsLong:
    .string "… … …\n"
    .string "… … …$"

Looker_Text_IThinkINeedTwoPokemon:
    .string "Hmm…\n"
    .string "I think I need two Pokémon for this…$"