Looker_Text_WhatSeemsToBeTheProblem:
    .string "What seems to be the problem?$"

Looker_Text_CanIHelpYouWithSomething:
    .string "Can I help you with something?$"

Looker_Text_IsSomethingWrong:
    .string "Is something wrong?$"

Looker_Text_HowCanIHelp:
    .string "How can I help?$"

Looker_Text_Understood:
    .string "Understood.$"

Looker_Text_IdBeHappyToHelp:
    .string "I'd be happy to help.$"

Looker_Text_GladICouldHelp:
    .string "Glad I could help.$"

Looker_Text_AnotherProblemSolved:
    .string "Another problem solved.$"

Looker_Text_OfCourse:
    .string "Of course.$"

Looker_Text_AlrightFine:
    .string "Alright, fine.$"

Looker_Text_SoHeresTheThing:
    .string "So here's the thing…$"
    
Looker_Text_Hmm:
    .string "Hmm…$"

Looker_Text_IHaveTheInformation:
    .string "I have the information you are looking\n"
    .string "for.$"

Looker_Text_SorryImBusy:
    .string "Sorry, I am busy.$"

Looker_Text_ICantHelpRightNow:
    .string "I can't help right now.$"

Looker_Text_LetMeThinkAboutThat:
    .string "Let me think about that.$"

Looker_Text_ThankYouForYourHelp:
    .string "Thank you for your help.$"

Looker_Text_ThankYouForTheIntel:
    .string "Thank you for the intel.$"

Looker_Text_Dots:
    .string "…$"

