Name_Unknown:
    .string " ??? $"

Name_Looker:
    .string "Looker$"

Name_Anabel:
    .string "Anabel$"

Name_Matt:
    .string "Matt$"

Name_Shelly:
    .string "Shelly$"

Name_Geoff:
    .string "Geoff$"

Name_Sarah:
    .string "Sarah$"

Name_Sheldon:
    .string "Sheldon$"
    
Name_Aqua_Grunt:
    .string "Aqua Grunt$"

Name_Mayor:
    .string "Mayor Morrigan$"

Name_Concerned_Dad:
    .string "Concerned Dad$"

Name_Estella:
    .string "Estella$"

Name_Head_Ranger:
    .string "Head Ranger$"

Name_Ranger:
    .string "Ranger$"

Name_Celebi:
    .string "Celebi$"

Name_Camilla:
    .string "Camilla$"

Name_Gym_Guy:
    .string "Gym Guide$"

Name_Phoebe:
    .string "Phoebe$"

Name_Tornadus:
    .string "Tornadus$"

Name_Thundurus:
    .string "Thundurus$"

Name_Scientist:
    .string "Scientist$"

Name_Lass:
    .string "Marie$"