Name_Unknown:
    .string " ??? $"

Name_Looker:
    .string "Looker$"

Name_Anabel:
    .string "Anabel$"

Name_Matt:
    .string "Matt$"

Name_Shelly:
    .string "Shelly$"

Name_Geoff:
    .string "Geoff$"

Name_Sarah:
    .string "Sarah$"

Name_Sheldon:
    .string "Sheldon$"
    
Name_Aqua_Grunt:
    .string "Aqua Grunt$"

Name_Mayor:
    .string "Mr. Morrigan$"

Name_Concerned_Dad:
    .string "Concerned Dad$"

Name_Relieved_Dad:
    .string "Relieved Dad$"

Name_Estella:
    .string "Estella$"

Name_Grandma:
    .string "Nina$"
    
Name_Head_Ranger:
    .string "Head Ranger$"

Name_Ranger:
    .string "Ranger$"

Name_Celebi:
    .string "Celebi$"

Name_Camilla:
    .string "Camilla$"

Name_Orator:
    .string "Village Elder$"

Name_Gym_Guy:
    .string "Gym Guide$"

Name_Phoebe:
    .string "Phoebe$"

Name_Tornadus:
    .string "Tornadus$"

Name_Thundurus:
    .string "Thundurus$"

Name_Present_FossilScientist:
    .string "Scientist$"

Name_Past_Maniac:
    .string "Everett$"

Name_Lass:
    .string "Marie$"

Name_Past_Fisherman:
    .string "Tee$"
    
Name_Present_Fisherman:
    .string "Trevor$"

Name_Past_Scientist:
    .string "Bartoz$"

Name_Left_Gameboy_Kid:
    .string "Gameboy Kid L$"

Name_Right_Gameboy_Kid:
    .string "Gameboy Kid R$"

Name_Cook:
    .string "Resigned Cook$"
    
Name_Magikarp_Man:
    .string "Shady Man$"

Name_Emma:
    .string "Emma$"
    
Name_Gentleman:
    .string "Gentleman$"

Name_Angry_Man:
    .string "Angry Man$"

Name_Calm_Man:
    .string "Calm Man$"

Name_Sentimental_Woman:
    .string "Melissa$"

Name_Sweet_Tooth:
    .string "Berryjammy$"

Name_Foreman:
    .string "Foreman Brown$"

Name_Carrot_Farmer:
    .string "Iris$"

Name_Cabbage_Farmer:
    .string "Damian$"

Name_Sick_Man:
    .string "Aesop$"

Name_Well_Man:
    .string "Aesop$"

Name_Nurse:
    .string "{PKMN} Nurse$"

Name_Farmgirl:
    .string "Alice$"

Name_Blue:
    .string "Blue$"

Name_May:
    .string "May$"

Name_Leaf:
    .string "Leaf$"

Name_Ace_Trainer:
    .string "Katherine$"

Name_Youngster:
    .string "Trey$"
    
Name_Right_Idol:
    .string "Sophia$"

Name_Left_Idol:
    .string "Bianca$"

Name_Lisia:
    .string "Lisia$"

Name_Barista:
    .string "Barista$"

Name_Student:
    .string "Paolo$"

Name_Beauty:
    .string "Beatrice$"

Name_Boyfriend:
    .string "Luca$"

Name_Artist:
    .string "Leo$"
    
Name_Aromatisse:
    .string "Aromatisse$"
    
Name_Smeargle:
    .string "Vinnie$"

Name_Twin:
    .string "Mia$"

Name_Doubter:
    .string "Nicola$"
    
Name_Dedenne:
    .string "Dedenne$"

Name_Togedemaru:
    .string "Togedemaru$"

Name_Lurantis:
    .string "Lurantis$"

Name_Luxray:
    .string "Luxray$"

Name_Toedscruel:
    .string "Toedscruel$"

Name_Frosmoth:
    .string "Frosmoth$"

Name_Kleavor:
    .string "Kleavor$"

Name_Goodra_Hisui:
    .string "Goodra-Hisui$"

Name_Beheeyem:
    .string "Beheeyem$"

Name_Aerodactyl:
    .string "Aerodactyl$"

Name_Scream_Tail:
    .string "Scream Tail$"

Name_Wo_Chien:
    .string "Wo-Chien$"
    
Name_Mochi_Man:
    .string "The Mochi Man$"

Name_Old_Lady:
    .string "Strange Lady$"

Name_Teacher:
    .string "Mrs. M.$"

Name_Councilwoman:
    .string "Christina$"

Name_Girl:
    .string "Girl$"

Name_GirlStudent:
    .string "Valentina$"