Past_House3_MapScripts::
	.byte 0

Past_House3_EventScript_OldWoman::
	msgbox Past_House3_Text_OldWoman, MSGBOX_NPC
	end

Past_House3_Text_OldWoman:
	.string "Oh, I remember the days when I\n"
	.string "traveled across time with Celebi!\p"
	.string "It is a rite of passage for many\n"
	.string "in the village!\p"
	.string "Be careful - wild POKéMON catch wind\n"
	.string "of the disturbance in the forest when\l"
	.string "you teleport!\p"
	.string "It's safe in this era, but if you walk\n"
	.string "through the woods in another time, you\l"
	.string "might run into some strong foes!$"